# Site
title: obsidian-mcp-brain
description: Remote MCP access to an Obsidian vault

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-default-layout

google_analytics: G-K1B7GJ3M5N

footer_content: '<a href="https://a1ecbr0wn.com"><img alt="a1ecbr0wn" src="https://img.shields.io/badge/a1ecbr0wn-home-brightgreen"></a> <img alt="License" src="https://img.shields.io/npm/l/obsidian-mcp-brain"> <a href="https://www.npmjs.com/package/obsidian-mcp-brain"><img alt="npm version" src="https://img.shields.io/npm/v/obsidian-mcp-brain"></a>'
aux_links:
  '<i class="fa-brands fa-2x fa-github"></i>':
    - "https://github.com/a1ecbr0wn/obsidian-mcp-brain"

exclude:
  - "/css/README.md"
